# Generated by Django 4.1 on 2022-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_superhero_description_superhero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
