name: plankton-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  github:
    branch: main
    deploy_on_push: true
    repo: elmoresiahaan/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: pythonwebapps-03-superhero
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: 03/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: elmoresiahaan/PythonWebApps
  name: pythonwebapps-03-superhero-stati
  routes:
  - path: /static
  source_dir: 03/Superhero/static